"""
Constants for the birdhouse model."""

import math

WALLTHICKNESS = 4.0  # mm

BIRDHOUSE_WIDTH = 60.0  # mm
BIRDHOUSE_DEPTH = 60.0  # mm
BIRDHOUSE_HEIGHT = 160.0  # mm
BIRDHOUSE_WIDTH_INNER = BIRDHOUSE_WIDTH - 2 * WALLTHICKNESS  # mm

BIRDHOUSE_SPACE_TOP = 35.0  # mm
BIRDHOUSE_SPACE_BOTTOM = 40.0  # mm

ROOF_HEIGHT = BIRDHOUSE_WIDTH / 2  # mm
ROOF_LENGTH = math.sqrt((BIRDHOUSE_WIDTH / 2) ** 2 + (ROOF_HEIGHT) ** 2)

SLIDE_LENGTH_MID = 20.0  # mm
SLIDE_LENGTH_TOP = SLIDE_LENGTH_MID
SLIDE_LENGTH_BOTTOM = math.sqrt(
    (BIRDHOUSE_DEPTH - WALLTHICKNESS) ** 2 + BIRDHOUSE_SPACE_BOTTOM**2
)
SLIDE_ANGLE = math.degrees(
    math.atan(BIRDHOUSE_SPACE_BOTTOM / (BIRDHOUSE_DEPTH - WALLTHICKNESS))
)

FRONT_PLATE_HEIGHT_MIDDLE = BIRDHOUSE_HEIGHT - BIRDHOUSE_SPACE_BOTTOM
FRONT_PLATE_HEIGHT_SIDE = FRONT_PLATE_HEIGHT_MIDDLE - ROOF_HEIGHT
SIDE_PLATE_HEIGHT = FRONT_PLATE_HEIGHT_SIDE + BIRDHOUSE_SPACE_BOTTOM
BACK_PLATE_HEIGHT = SIDE_PLATE_HEIGHT - BIRDHOUSE_SPACE_TOP
